version: '3'
services:
  selenium-mcp:
    build: .
    ports:
      - "8010:8000"  # FastAPI
      - "6090:6081"  # noVNC (mapped from container's 6081 to host's 6090)
      - "5910:5900"  # VNC
    environment:
      - DISPLAY=:1
    volumes:
      - .:/app
    restart: unless-stopped 