version: '3'

services:
  selenium-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8000"  # FastAPI
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    shm_size: '2gb'
    privileged: true
    depends_on:
      - selenium
    restart: unless-stopped 

  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 2gb 