version: '3.8'

services:
  selenium-mcp:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "6081:6080"  # noVNC
      - "5901:5900"  # VNC
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    shm_size: '2gb'
    privileged: true
    restart: unless-stopped 