"""update_schema_to_match_current_models

Revision ID: fc59fc448c6c
Revises: 377873f701bf
Create Date: 2025-06-21 00:23:37.525692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc59fc448c6c'
down_revision: Union[str, None] = '377873f701bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_session_id'), 'history', ['session_id'], unique=False)
    op.add_column('oauth_credentials', sa.Column('access_token', sa.Text(), nullable=False))
    op.add_column('oauth_credentials', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('oauth_credentials', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('oauth_credentials', sa.Column('scopes', sa.Text(), nullable=True))
    op.drop_column('oauth_credentials', 'credentials_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_credentials', sa.Column('credentials_json', sa.TEXT(), nullable=False))
    op.drop_column('oauth_credentials', 'scopes')
    op.drop_column('oauth_credentials', 'expires_at')
    op.drop_column('oauth_credentials', 'refresh_token')
    op.drop_column('oauth_credentials', 'access_token')
    op.drop_index(op.f('ix_history_session_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
