"""Update OAuth credentials schema to store tokens separately

Revision ID: 119f4060f94f
Revises: 
Create Date: 2025-06-14 23:39:41.912447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119f4060f94f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('credentials_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials_json', sa.TEXT(), nullable=False))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
